import {Button} from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>3gram - privacy focussed web3 photo and video sharing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="py-6 text-8xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-500">
          3gram
        </h1>
        <p className="mb-6 text-2xl font-bold text-slate-600">
          Privacy focussed web3 photo and video sharing
        </p>
        {/* TODO: replace with rainbow kit button */}

        <Button colorScheme="messenger">Connect Wallet</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Web3
        </a>
      </footer>
    </div>
  );
}
